doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Vehicle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Vehicle/Domain/Entity'
                prefix: 'App\Vehicle\Domain\Entity'
                alias: Vehicle
            VehicleValueObject:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Vehicle/Domain/ValueObject'
                prefix: 'App\Vehicle\Domain\ValueObject'
                alias: VehicleValueObject
            Driver:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Driver/Domain/Entity'
                prefix: 'App\Driver\Domain\Entity'
                alias: Driver
            DriverValueObject:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Driver/Domain/ValueObject'
                prefix: 'App\Driver\Domain\ValueObject'
                alias: DriverValueObject
            Trip:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Trip/Domain/Entity'
                prefix: 'App\Trip\Domain\Entity'
                alias: Trip

        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
